package reilly.projecteular.problems.oldanddonotwork;    /*
     *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     *  By starting with 1 and 2, the first 10 terms will be:
     *  
     *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     *  Find the sum of all the even-valued terms in the sequence which do not exceed one million.
     *
     */

class Problem2
{
    public static void main(String[] args) {
        int x1 = 1;
        int x2 = 2;
        int temp = 0;
        int counter = 2;

        do {
            temp = x2;
            x2 += x1;
            x1 = temp;
            if (x2 % 2 == 0) {
                counter += x2;  
            }
        } while (x2 < 999999);
        System.out.println("counter = "+counter);
    }
}
